name: flutter_deep_linking
description: A Flutter sample showing off deep linking
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:  
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  collection: ^1.15.0
  cupertino_icons: ^1.0.2

  path_to_regexp: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
